version: 2

updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/docker/*"
    schedule:
      interval: "daily"
    groups:
      docker-images:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "terraform"
    directories:
      - "/terraform/**"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      terraform-providers:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
