---
services:
  stirling-pdf:
    image: ghcr.io/stirling-tools/stirling-pdf:0.46.2
    container_name: stirling-pdf
    restart: on-failure:5
    networks:
      - proxynet
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${DOCKER_BASE_PATH}/stirling-pdf/data:/usr/share/tessdata:rw # Required for extra OCR languages
      - ${DOCKER_BASE_PATH}/stirling-pdf/config:/configs:rw
      - ${DOCKER_BASE_PATH}/stirling-pdf/logs:/logs:rw
    environment:
     PUID: ${PUID}
     PGID: ${PGID}
     DOCKER_ENABLE_SECURITY: ${DOCKER_ENABLE_SECURITY}
     SECURITY_ENABLELOGIN: ${SECURITY_ENABLELOGIN}
     SECURITY_INITIALLOGIN_USERNAME: ${SECURITY_INITIALLOGIN_USERNAME}
     SECURITY_INITIALLOGIN_PASSWORD: ${SECURITY_INITIALLOGIN_PASSWORD}  
     INSTALL_BOOK_AND_ADVANCED_HTML_OPS: ${INSTALL_BOOK_AND_ADVANCED_HTML_OPS}
     SECURITY_CSRFDISABLED: ${SECURITY_CSRFDISABLED}
     SYSTEM_DEFAULTLOCALE: ${SYSTEM_DEFAULTLOCALE}
     SYSTEM_MAXFILESIZE: ${SYSTEM_MAXFILESIZE}
     METRICS_ENABLED: ${METRICS_ENABLED}
     SYSTEM_GOOGLEVISIBILITY: ${SYSTEM_GOOGLEVISIBILITY}
    labels:
      - traefik.enable=true
      - traefik.http.services.stirling-pdf.loadbalancer.server.port=8080
      - traefik.http.routers.stirling-pdf.rule=Host(`stirling-pdf.${TRAEFIK_BASE_DOMAIN}`)
      - traefik.http.routers.stirling-pdf.entrypoints=websecure
      - traefik.http.routers.stirling-pdf.tls=true
      - traefik.http.routers.stirling-pdf.tls.certresolver=cloudns

networks:
  proxynet:
    external: true