services:
  handbrake:
    image: ghcr.io/jlesage/handbrake:v25.07.2
    container_name: handbrake
    restart: unless-stopped
    networks:
      - proxynet
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${DOCKER_BASE_PATH}/handbrake:/config
      - ${BACKUP_PATH}:/storage/Backups
      - ${MEDIA_PATH}:/storage/Media
      - ${MEDIA_PATH}/Videos/temp/Output:/output
    environment:
      USER_ID: ${PUID}
      GROUP_ID: ${PGID}
      TZ: ${TZ}
      UMASK: ${UMASK}
    labels:
      - traefik.enable=true
      - traefik.http.services.handbrake.loadbalancer.server.port=5800
      - traefik.http.routers.handbrake.rule=Host(`handbrake.${TRAEFIK_BASE_DOMAIN}`)
      - traefik.http.routers.handbrake.entrypoints=websecure
      - traefik.http.routers.handbrake.tls=true
      - traefik.http.routers.handbrake.tls.certresolver=cloudns

networks:
  proxynet:
    external: true
