services:
  nginx-proxy-manager:
    image: docker.io/jc21/nginx-proxy-manager:2.12.4
    container_name: nginx-proxy-manager
    restart: unless-stopped
    networks:
      - proxynet
    ports:
      - '80:80'
      # - '8181:81'
      - '443:443'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DOCKER_BASE_PATH}/nginx-proxy-manager/data:/data
      - ${DOCKER_BASE_PATH}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

networks:
  proxynet:
    external: true