services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:0.7.6-nbxyz4
    container_name: netbootxyz
    restart: unless-stopped
    networks:
      - proxynet
    ports:
    - 69:69/udp
    - 8080:80
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      NGINX_PORT: ${NGINX_PORT}
      WEB_APP_PORT: ${WEB_APP_PORT}
    volumes:
      - ${DOCKER_BASE_PATH}/netbootxyz/config:/config
      - ${DOCKER_BASE_PATH}/netbootxyz/assets:/assets
    labels:
      - traefik.enable=true
      - traefik.http.services.metube.loadbalancer.server.port=3000
      - traefik.http.routers.metube.rule=Host(`${TRAEFIK_HOSTNAME}`)
      - traefik.http.routers.metube.entrypoints=websecure
      - traefik.http.routers.metube.tls=true
      - traefik.http.routers.metube.tls.certresolver=${TRAEFIK_CERTRESOLVER}

networks:
  proxynet:
    external: true