#cloud-config
# Ubuntu 26.04 autoinstall template for dh01 (bare metal, Intel N150).
#
# DO NOT edit this file with actual secrets — it lives in the public repo.
# Generate the real user-data with:
#   docker/netbootxyz/scripts/generate-autoinstall-userdata.sh
#
# Variables substituted at generate time (defined in .envrc):
#   ${DH01_HOSTNAME}        hostname for dh01 (default: dh01)
#   ${ADMIN_USER}           admin username   (default: ubuntu)
#   ${PASSWORD_HASH}        hashed password  (generate: openssl passwd -6 'pass')
#   ${NAS_IP}               NAS IP address
#   ${NAS_MEDIA_EXPORT}     NFS media export path   (e.g. /volume1/Media)
#   ${NAS_SHARED_EXPORT}    NFS docker export path  (e.g. /volume1/docker)
#   ${NAS_BACKUPS_EXPORT}   NFS backups export path (e.g. /volume1/Backups)
#   ${GITHUB_USER}          GitHub username for ssh-import-id (default: locus313)
#   ${REPO_URL}             homelab-gitops repo URL

autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us

  identity:
    hostname: ${DH01_HOSTNAME}
    realname: "Homelab Admin"
    username: ${ADMIN_USER}
    password: "${PASSWORD_HASH}"

  ssh:
    install-server: true
    allow-pw: false  # Key-only auth; SSH keys imported via user-data runcmd

  # Wipe and use the entire largest disk; no LVM
  storage:
    layout:
      name: direct
      match:
        size: largest

  # Packages installed during the Ubuntu installer phase (before first reboot)
  packages:
    - ca-certificates
    - curl
    - git
    - nfs-common

  # First-boot cloud-config — runs after the installer reboots into the installed system.
  # Mirrors the SC VM cloud-init setup (terraform/homelab/assets/user-data.docker-host.yml.tftpl)
  # with adjustments for bare metal (no qemu-guest-agent, no ScaleComputing GRUB tuning).
  user-data:
    timezone: America/Los_Angeles
    package_update: true
    package_upgrade: true

    write_files:
      # Disable root SSH login and enforce key-only authentication
      - path: /etc/ssh/sshd_config.d/99-homelab.conf
        permissions: "0600"
        content: |
          PermitRootLogin no
          PasswordAuthentication no

      # Enable automatic security updates via unattended-upgrades
      - path: /etc/apt/apt.conf.d/20auto-upgrades
        permissions: "0644"
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::AutocleanInterval "7";

      # Unattended-upgrades: all updates, auto-reboot at 03:00 if required
      - path: /etc/apt/apt.conf.d/51homelab-unattended-upgrades
        permissions: "0644"
        content: |
          Unattended-Upgrade::Allowed-Origins {
              "${distro_id}:${distro_codename}";
              "${distro_id}:${distro_codename}-updates";
              "${distro_id}:${distro_codename}-security";
              "${distro_id}ESMApps:${distro_codename}-apps-security";
              "${distro_id}ESM:${distro_codename}-infra-security";
          };
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          Unattended-Upgrade::Automatic-Reboot "true";
          Unattended-Upgrade::Automatic-Reboot-Time "03:00";

      # Docker daemon: cap container log size to prevent disk fill-up
      - path: /etc/docker/daemon.json
        permissions: "0644"
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }

      # sysctl tuning for Docker workloads
      - path: /etc/sysctl.d/99-homelab.conf
        permissions: "0644"
        content: |
          vm.max_map_count=262144
          vm.swappiness=10

      # NFS fstab entries — appended to /etc/fstab by runcmd
      - path: /etc/fstab.d/nfs-homelab.conf
        permissions: "0644"
        content: |
          ${NAS_IP}:${NAS_MEDIA_EXPORT}    /mnt/media    nfs  defaults,nfsvers=4,hard,intr,_netdev  0  0
          ${NAS_IP}:${NAS_SHARED_EXPORT}   /mnt/docker   nfs  defaults,nfsvers=4,hard,intr,_netdev  0  0
          ${NAS_IP}:${NAS_BACKUPS_EXPORT}  /mnt/backups  nfs  defaults,nfsvers=4,hard,intr,_netdev  0  0

    runcmd:
      # Apply SSH hardening immediately
      - systemctl restart ssh

      # Apply sysctl tuning immediately (also persists via /etc/sysctl.d/)
      - sysctl -p /etc/sysctl.d/99-homelab.conf

      # Create and enable a 4 GB swapfile (Ubuntu server has no swap by default)
      - fallocate -l 4G /swapfile
      - chmod 600 /swapfile
      - mkswap /swapfile
      - swapon /swapfile
      - sh -c 'echo "/swapfile none swap sw 0 0" >> /etc/fstab'

      # Install Docker Engine from Docker's official apt repository
      - install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      - chmod a+r /etc/apt/keyrings/docker.asc
      - sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list'
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - systemctl enable docker
      - systemctl start docker
      - usermod -aG docker ${ADMIN_USER}

      # Create mount point directories
      - mkdir -p /mnt/media /mnt/docker /mnt/backups /docker

      # Append NFS entries to /etc/fstab and mount
      - cat /etc/fstab.d/nfs-homelab.conf >> /etc/fstab
      - mount -a || true

      # Create the shared Docker network used by all homelab services
      - docker network create proxynet

      # Import SSH public keys from GitHub
      - ssh-import-id-gh ${GITHUB_USER}

      # Clone the homelab-gitops repo
      - git clone ${REPO_URL} /opt/homelab-gitops
