services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    restart: unless-stopped
    networks:
      - proxynet
    labels:
      - traefik.enable=true
      - traefik.http.services.it-tools.loadbalancer.server.port=80
      - traefik.http.routers.it-tools.rule=Host(`it-tools.${TRAEFIK_BASE_DOMAIN}`)
      - traefik.http.routers.it-tools.entrypoints=websecure
      - traefik.http.routers.it-tools.tls=true
      - traefik.http.routers.it-tools.tls.certresolver=cloudns

networks:
  proxynet:
    external: true
