services:
  eonvelope:
    image: dacid99/eonvelope:0.7.1
    container_name: eonvelope
    restart: unless-stopped
    depends_on:
      eonvelope-db:
        condition: service_healthy
    networks:
      - proxynet
    volumes:
      - ${DOCKER_BASE_PATH}/eonvelope/archive:/mnt/archive
      - ${DOCKER_BASE_PATH}/eonvelope/log:/var/log/eonvelope
    environment:
      TZ: ${TZ}
      DATABASE: ${EONVELOPE_DB_NAME}
      DATABASE_USER: ${EONVELOPE_DB_USER}
      DATABASE_PASSWORD: ${EONVELOPE_DB_PASSWORD}
      DATABASE_HOST: eonvelope-db
      SECRET_KEY: ${EONVELOPE_SECRET_KEY}
      DJANGO_SUPERUSER_PASSWORD: ${EONVELOPE_ADMIN_PASSWORD}
      ALLOWED_HOSTS: localhost,eonvelope.${TRAEFIK_BASE_DOMAIN}
      CSRF_TRUSTED_ORIGINS: https://eonvelope.${TRAEFIK_BASE_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.services.eonvelope.loadbalancer.server.port=443
      - traefik.http.services.eonvelope.loadbalancer.server.scheme=https
      - traefik.http.routers.eonvelope.rule=Host(`eonvelope.${TRAEFIK_BASE_DOMAIN}`)
      - traefik.http.routers.eonvelope.entrypoints=websecure
      - traefik.http.routers.eonvelope.tls=true
      - traefik.http.routers.eonvelope.tls.certresolver=cloudns

  eonvelope-db:
    image: mariadb:11.4
    container_name: eonvelope-db
    restart: unless-stopped
    networks:
      - proxynet
    volumes:
      - ${DOCKER_BASE_PATH}/eonvelope/db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${EONVELOPE_DB_NAME}
      MARIADB_USER: ${EONVELOPE_DB_USER}
      MARIADB_PASSWORD: ${EONVELOPE_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${EONVELOPE_DB_ROOT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb -u$$MARIADB_USER -p$$MARIADB_PASSWORD -e 'SELECT 1'",
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

networks:
  proxynet:
    external: true
