http:
  routers:
    portainer:
      entryPoints:
        - websecure
      rule: 'Host(`portainer.{{ env "TRAEFIK_BASE_DOMAIN" }}`)'
      service: portainer-svc
      tls:
        certResolver: cloudns

  services:
    portainer-svc:
      loadBalancer:
        servers:
          - url: "https://portainer:9443"
