services:
  traefik:
    image: traefik:v3.4.3
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxynet
    ports:
      - 80:80
      - 443:443
      - 8181:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_BASE_PATH}/traefik/config:/etc/traefik:ro
      - ${DOCKER_BASE_PATH}/traefik/certs:/var/traefik/certs/:rw
    environment:
      CLOUDNS_AUTH_ID: ${CLOUDNS_AUTH_ID}
      CLOUDNS_AUTH_PASSWORD: ${CLOUDNS_AUTH_PASSWORD}

networks:
  proxynet:
    external: true