services:
  traefik:
    image: traefik:v3.4.3
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxynet
    ports:
      - 80:80
      - 443:443
      - 8181:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_BASE_PATH}/traefik/config:/etc/traefik:ro
      - ${DOCKER_BASE_PATH}/traefik/certs:/var/traefik/certs/:rw
      - ${DOCKER_BASE_PATH}/traefik/logs:/logs
    environment:
      CLOUDNS_SUB_AUTH_ID: ${CLOUDNS_SUB_AUTH_ID}
      CLOUDNS_AUTH_PASSWORD: ${CLOUDNS_AUTH_PASSWORD}
      DOMAINNAME: ${DOMAINNAME}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAINNAME}`)
      - traefik.http.routers.traefik-rtr.service=api@internal
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.tls.certresolver=${ACME_DNSCHALLENGE_PROVIDER}

networks:
  proxynet:
    external: true